#!/usr/bin/python3
## depends: python3-requests python3-requests-toolbelt

import argparse
import os
import fileinput
import requests
from requests_toolbelt.multipart.encoder import MultipartEncoder

# Default settings should be changed ~/.onetimepasterc
# TODO
url="https://enviosecreto.es"
cli_auth="canihazpastes?"

def upload(tipo, contenido):
  print("Sending...")
  if tipo == "file":
    multipart_data = MultipartEncoder(
      fields={
              # a file upload field
              'file': (contenido, open(contenido, 'rb'), 'application/octet-stream'),
              # plain text fields
              'type': tipo,
              'cli_auth': cli_auth,
             }
      )
  elif tipo == "message":
    multipart_data = MultipartEncoder(
      fields={
              'message': contenido,
              'type': tipo,
              'cli_auth': cli_auth,
             }
      )
  response = requests.post(url + "/api.php", data=multipart_data,
     headers={'Content-Type': multipart_data.content_type})
  print(response.text)

##############

parser = argparse.ArgumentParser(description='Send encrypted messages or files using ' + url)
parser.add_argument("-t", "--text", help="Upload file as text message", action="store_true")
# nargs=? permite que un parámetro posicional sea opcional
parser.add_argument("message", metavar='message|FILE', nargs='?', help="Text message or file to upload. stdin if ommited")

argumentos = parser.parse_args()

if argumentos.message and os.path.isfile(argumentos.message) and not argumentos.text:
  upload("file", argumentos.message)
else:
  mensaje=""
  if argumentos.message and os.path.isfile(argumentos.message):
    for linea in fileinput.input(files=argumentos.message):
      mensaje+=linea
  elif (argumentos.message and argumentos.message == "-") or not argumentos.message:
    for linea in fileinput.input():
      mensaje+=linea
  else:
    mensaje = argumentos.message

  upload("message", mensaje)

